// Copies the dual-format `#require` helper into both build outputs and adds the
// `#require` subpath import to the package.json files generated by esm2cjs.
// Node only honors conditional `imports`/`exports` for package-name and `#`-prefixed
// specifiers, and resolves them against the *nearest* package.json — which for the
// built files is build/esm/package.json or build/cjs/package.json, not the root one.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const files = ['require.cjs', 'require.mjs', 'require.d.ts'];

for (const format of ['esm', 'cjs']) {
    const outDir = join('build', format, 'require');
    mkdirSync(outDir, { recursive: true });
    for (const file of files) {
        copyFileSync(join('src', 'require', file), join(outDir, file));
    }

    const pkgPath = join('build', format, 'package.json');
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    pkg.imports = {
        '#require': {
            types: './require/require.d.ts',
            esbuild: './require/require.cjs',
            import: './require/require.mjs',
            require: './require/require.cjs',
        },
    };
    writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 4)}\n`);
}
